#!/bin/bash

cd /app

echo """


                                                                                          
PragyanX                                                                                
                    

"""

gunicorn -b :5000 --reload --access-logfile - --error-logfile - app:app
